// <auto-generated> 
using Microsoft.EntityFrameworkCore.Migrations;

namespace CasesNET.Data.Migrations
{
    public partial class updatemanufacturerforeignkeytoimage : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Manufacturers_Images_ImageUrl",
                table: "Manufacturers");

            migrationBuilder.DropIndex(
                name: "IX_Manufacturers_ImageUrl",
                table: "Manufacturers");

            migrationBuilder.DropColumn(
                name: "ImageUrl",
                table: "Manufacturers");

            migrationBuilder.AddColumn<string>(
                name: "ImageId",
                table: "Manufacturers",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Manufacturers_ImageId",
                table: "Manufacturers",
                column: "ImageId");

            migrationBuilder.AddForeignKey(
                name: "FK_Manufacturers_Images_ImageId",
                table: "Manufacturers",
                column: "ImageId",
                principalTable: "Images",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Manufacturers_Images_ImageId",
                table: "Manufacturers");

            migrationBuilder.DropIndex(
                name: "IX_Manufacturers_ImageId",
                table: "Manufacturers");

            migrationBuilder.DropColumn(
                name: "ImageId",
                table: "Manufacturers");

            migrationBuilder.AddColumn<string>(
                name: "ImageUrl",
                table: "Manufacturers",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Manufacturers_ImageUrl",
                table: "Manufacturers",
                column: "ImageUrl",
                unique: true,
                filter: "[ImageUrl] IS NOT NULL");

            migrationBuilder.AddForeignKey(
                name: "FK_Manufacturers_Images_ImageUrl",
                table: "Manufacturers",
                column: "ImageUrl",
                principalTable: "Images",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
